### ISSUE TITLE
Topic: is minifabric too powerful than being mini?

### ISSUE THREAD

**Issue by davidkhala** [litong01/minifabric#33]
Along the time, I feel minifabric take too much capability into consider and make the document and code as long as the feature growth. 

Could we end up at the point `chaincode operation` and no further? It would be hard to keep track of all type of sdk connection profile change.

**Comment by litong01** [comment]
@davidkhala since it is very modular, adding different connection profile is basically a template, that is the reason why minifabric can support so many different kind. I totally understand the frustration of having so many different kind connection profiles, I would actually like to talk to different sdks devs and see if somehow we can unify all the connection profiles so that we do not end up with so many kinds.

**Comment by davidkhala** [comment]
@litong01 a crazy idea come into my mind is if we could make connection profile as part of sample config just like configtx.yml
Then it will be a recommended and single point standard.

**Comment by litong01** [comment]
@davidkhala can you elaborate a bit more on this?

**Comment by litong01** [comment]
@davidkhala @edkaz I have asked Dave Enyeart to schedule a talk in the Fabric dev meeting to introduce minifabric, I wonder if you guys want to do that? I can do it but it will be rather doll since I developed it. @edkaz Since you have used in your dev, the statement from you is probably more powerful. The goal of this project is to make it a first class project under Hyperledger to help people learn, use, deploy, develop Fabric. Since I do not have you guys contact, I have to use this thread for this discussion, please respond. The talk is scheduled on 7/8, 10am EDT I think.

**Comment by davidkhala** [comment]
> @davidkhala can you elaborate a bit more on this?

This is outside this project scope, I meant, Fabric maintainer could have setup an standard connection profile syntax format for all sdks and ask sdk maintainers to follow.

**Comment by litong01** [comment]
@davidkhala correct. my hope is that we ask sdk developers to work together to have an unified connection profile, then all sdks use that format. to minifabric, we will just produce one which can be used by project using any sdk. This work is not part of minifabric.

**Comment by ChrisSargent** [comment]
Just to add to this, I feel the generation of the connection profile is one of the best features of Minifab. For example, there is a decent amount of documentation and tutorials around about getting chaincode running in Hyperledger but not so much about getting an API / Client application to communicate with it, especially if you're using the GO SDK. The only one I know about is the Chainheros one and that is quite out of date now.

Any help or comments I can give about unifying the connection profile, just let me know, but I think it is essential that the profile be standardised across languages and SDKs.

As a client application or chaincode developer, I literally don't want to get involved or even care about the network underneath (or at least it's configuration).

**Comment by edkaz** [comment]
I really want to echo Chris Sargent's words in the previous. Minifab has allowed me to cut my network development time to fraction of what it was before. Unfortunately I am involved in network configuration and Minicab has helped reduce my prototyping and testing turnaround time hugely.  BUT the one feature that I rely day to day is the  is the generation of __connection profiles__ which makes the process of developing client/chaincode interaction so much simpler. 

I work in NodeJS so if I can do likewise and offer help or comments regarding NodeJS then let me know.

**Comment by litong01** [comment]
close this since there is no action need to be taken.
