### ISSUE TITLE
Config more than spec.yaml 

### ISSUE THREAD

**Issue by davidkhala** [litong01/minifabric#35]
https://github.com/davidkhala/delphi-fabric/blob/master/config/orgs.json
This is a sample of my daily used project configuration json
I am thinking if I could use minifabric as alternative docker network bootstrap tool, while I could not find the essential following configurartion in `spec.yaml`
- mspid
- host port used for each container
- docker network name

I guess there is a default mechanism to handle this implicitly. But I get lost in documents.

**Comment by litong01** [comment]
if we allow customized mspid, then configuration can become very large. host port can be controlled by supply -e 7778 for example, then the starting port will be 7778, other nodes will use port based on that number. It is not a complete customization, but one has to always battle the simplicity and the flexibility. docket network name is currently hard coded. Again, I think that the issue is the balance of the simplicity and the flexibility. We can easily add a configuration parameter in the spec.yaml file, but again the spec may become rather large, of course we can make a lot of default values as well.

**Comment by davidkhala** [comment]
So I summarize along with our offline conversions
- **Organization Name** for each node is the rest part of domain name after first dot `.`
- **mspid** for each Organization is the translated **Organization Name** by substituting all dot `.` with `-`
- host **port** is generated as incremental sequences of starting port number (supplied in -e 7778)

Example
> peer0.org1.com --> mspid = org1-com, organization name = org1.com hostPort=7778
> peer1.org1.com --> mspid = org1-com, organization name = org1.com hostPort=7779
> peer0.org2.com --> mspid = org2-com, organization name = org2.com hostPort=7780

**Comment by litong01** [comment]
@davidkhala yes. that is exactly right.

**Comment by litong01** [comment]
@davidkhala will you add some doc to close out this issue? I mean add some content on how these things get generated and how one can take advantages of these conventions.

**Comment by davidkhala** [comment]
> @davidkhala will you add some doc to close out this issue? I mean add some content on how these things get generated and how one can take advantages of these conventions.

Sure, I was occupied these days. Please ping me if me forget about this again.
