### ISSUE TITLE
Could not join a new organisation

### ISSUE THREAD

**Issue by crizaqcri** [litong01/minifabric#84]
I have followed the tutorial from https://www.youtube.com/watch?v=c1Ab57IrgZg&list=PL0MZ85B_96CExhq0YdHLPS5cmSBvSmwyO&index=4 

On one machine I have a network with 2 organisations, 2 peers, ca, orderes. 
On the second machine I have a single oranisation with 2 peers

The first network works fine, I can invoke chaincodes and get the correct response, I have updated the config file with the json from the new organisation, sign and update channel with success. 

But on the second organisation I am not able to install any chaincode, if I try to get the channel config it returns an empty file. I have imported the enpoints certificates from the existent network. 

Spec for new org:
fabric:
  peers: 
  - "peer1.org4.cri.com"
  - "peer2.org4.cri.com"

On the second machine the peers are up but the logs are full of warning that they can not see each other:

2020-10-02 08:46:19.097 UTC [gossip.discovery] func1 -> WARN 098 Could not connect to Endpoint: 192.168.110.33:7000, InternalEndpoint: 192.168.110.33:7000, PKI-ID: <nil>, Metadata:  : context deadline exceeded

On the second machine the following commands has been run with success:
./minifab netup -s couchdb -e true -o org4.cri.com
./minifab nodeimport

Error when trying to install the chaincode:
Error: Failed to retrieve endorser client for install: endorser client failed to connect to 192.168.110.33:7000: failed to create new connection: context deadline exceeded
Port 7000 is for peer1.org4.cri.com 

Any idea why peers from the second network are not working correctly?

**Comment by litong01** [comment]
@crizaqcri general process is this.

1. On 2st machine, stand up a fabric network and make sure you have orderer, peer and everything is running. basically use `minifab up -e true`
2. On 2nd machine, stand up another org with peers and make sure peer nodes are running, basically use `minifab netup -e true -o xxx`
3. on the first machine, copy the org join request file in vars directory from the 2nd machine, and follow the new org join process describe here https://github.com/litong01/minifabric/blob/master/docs/AddNewOrganization.md.
4. on the 2nd machine, import orderer nodes and join peer to the channel which was created at step 1. default is `mychannel`
5. on the 2nd machine, install chaincode, approve, commit
6, on the 2nd machine, you would also need to do `minifab discovery` after join, so that the 2nd machine now knows other organizations and peers, then you can do 'minifab invoke`

without the last step, chaincode invocation will fail because the org on the 2nd machine would not have know anything about the other org's peers. 

You also need to make sure that ports are exported when setting up nodes using`-e true`, and make sure that two machines can communicate with each other, if you have firewall etc, you will have to make sure that the firewall are open for the ports which orderer and peer node will use. I normally use two or three different working directories on one machine to mimic these scenarios but specify starting ports such as this `-e 7000` for one site, and `-e 7200` for another and `-e 7400` for the 3rd, so that I am not having port conflicts when running 3 or more orgs on the same machine.

**Comment by crizaqcri** [comment]
Thank you. I did these steps but at step 5 when I tried to perform install on the second machine it failed. I will try to test on a single machine with -e 7000 option.

**Comment by crizaqcri** [comment]
I reconstructed the network on the same machine, now my new organisation is visible in the network. But I can not manage to commit the chaincode 

./minifab commit -c mychannel -n samplecc

# Run the chaincode commit script on cli container ************
  non-zero return code
  2020-10-05 10:49:15.288 UTC [chaincodeCmd] ClientWait -> INFO 001 txid [467bb16c47c152a6a38924b325acf798e966263c9553a5359024a4c9f5a46f6a] committed with status (ENDORSEMENT_POLICY_FAILURE) at 25.41.86.164:7200
  Error: transaction invalidated with status (ENDORSEMENT_POLICY_FAILURE)

# STATS *****************************************************

What can be the problem?

**Comment by litong01** [comment]
I suggest that you close this comment and create new one with really clear steps so one want to help can reproduce your issue. Otherwise, people will have hard time to understand what you are doing and can not figure out the step you took.

**Comment by crizaqcri** [comment]
Ok, I will create a new task.
